# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/amanshenoy/Desktop/projects/github/object-viewer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/amanshenoy/Desktop/projects/github/object-viewer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amanshenoy/Desktop/projects/github/object-viewer/CMakeFiles /home/amanshenoy/Desktop/projects/github/object-viewer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amanshenoy/Desktop/projects/github/object-viewer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named object-viewer

# Build rule for target.
object-viewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 object-viewer
.PHONY : object-viewer

# fast build rule for target.
object-viewer/fast:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/build
.PHONY : object-viewer/fast

src/dependancies/imgui/imgui.o: src/dependancies/imgui/imgui.cpp.o

.PHONY : src/dependancies/imgui/imgui.o

# target to build an object file
src/dependancies/imgui/imgui.cpp.o:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/dependancies/imgui/imgui.cpp.o
.PHONY : src/dependancies/imgui/imgui.cpp.o

src/dependancies/imgui/imgui.i: src/dependancies/imgui/imgui.cpp.i

.PHONY : src/dependancies/imgui/imgui.i

# target to preprocess a source file
src/dependancies/imgui/imgui.cpp.i:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/dependancies/imgui/imgui.cpp.i
.PHONY : src/dependancies/imgui/imgui.cpp.i

src/dependancies/imgui/imgui.s: src/dependancies/imgui/imgui.cpp.s

.PHONY : src/dependancies/imgui/imgui.s

# target to generate assembly for a file
src/dependancies/imgui/imgui.cpp.s:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/dependancies/imgui/imgui.cpp.s
.PHONY : src/dependancies/imgui/imgui.cpp.s

src/dependancies/imgui/imgui_demo.o: src/dependancies/imgui/imgui_demo.cpp.o

.PHONY : src/dependancies/imgui/imgui_demo.o

# target to build an object file
src/dependancies/imgui/imgui_demo.cpp.o:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/dependancies/imgui/imgui_demo.cpp.o
.PHONY : src/dependancies/imgui/imgui_demo.cpp.o

src/dependancies/imgui/imgui_demo.i: src/dependancies/imgui/imgui_demo.cpp.i

.PHONY : src/dependancies/imgui/imgui_demo.i

# target to preprocess a source file
src/dependancies/imgui/imgui_demo.cpp.i:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/dependancies/imgui/imgui_demo.cpp.i
.PHONY : src/dependancies/imgui/imgui_demo.cpp.i

src/dependancies/imgui/imgui_demo.s: src/dependancies/imgui/imgui_demo.cpp.s

.PHONY : src/dependancies/imgui/imgui_demo.s

# target to generate assembly for a file
src/dependancies/imgui/imgui_demo.cpp.s:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/dependancies/imgui/imgui_demo.cpp.s
.PHONY : src/dependancies/imgui/imgui_demo.cpp.s

src/dependancies/imgui/imgui_draw.o: src/dependancies/imgui/imgui_draw.cpp.o

.PHONY : src/dependancies/imgui/imgui_draw.o

# target to build an object file
src/dependancies/imgui/imgui_draw.cpp.o:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/dependancies/imgui/imgui_draw.cpp.o
.PHONY : src/dependancies/imgui/imgui_draw.cpp.o

src/dependancies/imgui/imgui_draw.i: src/dependancies/imgui/imgui_draw.cpp.i

.PHONY : src/dependancies/imgui/imgui_draw.i

# target to preprocess a source file
src/dependancies/imgui/imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/dependancies/imgui/imgui_draw.cpp.i
.PHONY : src/dependancies/imgui/imgui_draw.cpp.i

src/dependancies/imgui/imgui_draw.s: src/dependancies/imgui/imgui_draw.cpp.s

.PHONY : src/dependancies/imgui/imgui_draw.s

# target to generate assembly for a file
src/dependancies/imgui/imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/dependancies/imgui/imgui_draw.cpp.s
.PHONY : src/dependancies/imgui/imgui_draw.cpp.s

src/dependancies/imgui/imgui_impl_glfw.o: src/dependancies/imgui/imgui_impl_glfw.cpp.o

.PHONY : src/dependancies/imgui/imgui_impl_glfw.o

# target to build an object file
src/dependancies/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/dependancies/imgui/imgui_impl_glfw.cpp.o
.PHONY : src/dependancies/imgui/imgui_impl_glfw.cpp.o

src/dependancies/imgui/imgui_impl_glfw.i: src/dependancies/imgui/imgui_impl_glfw.cpp.i

.PHONY : src/dependancies/imgui/imgui_impl_glfw.i

# target to preprocess a source file
src/dependancies/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/dependancies/imgui/imgui_impl_glfw.cpp.i
.PHONY : src/dependancies/imgui/imgui_impl_glfw.cpp.i

src/dependancies/imgui/imgui_impl_glfw.s: src/dependancies/imgui/imgui_impl_glfw.cpp.s

.PHONY : src/dependancies/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
src/dependancies/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/dependancies/imgui/imgui_impl_glfw.cpp.s
.PHONY : src/dependancies/imgui/imgui_impl_glfw.cpp.s

src/dependancies/imgui/imgui_impl_opengl3.o: src/dependancies/imgui/imgui_impl_opengl3.cpp.o

.PHONY : src/dependancies/imgui/imgui_impl_opengl3.o

# target to build an object file
src/dependancies/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/dependancies/imgui/imgui_impl_opengl3.cpp.o
.PHONY : src/dependancies/imgui/imgui_impl_opengl3.cpp.o

src/dependancies/imgui/imgui_impl_opengl3.i: src/dependancies/imgui/imgui_impl_opengl3.cpp.i

.PHONY : src/dependancies/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
src/dependancies/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/dependancies/imgui/imgui_impl_opengl3.cpp.i
.PHONY : src/dependancies/imgui/imgui_impl_opengl3.cpp.i

src/dependancies/imgui/imgui_impl_opengl3.s: src/dependancies/imgui/imgui_impl_opengl3.cpp.s

.PHONY : src/dependancies/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
src/dependancies/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/dependancies/imgui/imgui_impl_opengl3.cpp.s
.PHONY : src/dependancies/imgui/imgui_impl_opengl3.cpp.s

src/dependancies/imgui/imgui_widgets.o: src/dependancies/imgui/imgui_widgets.cpp.o

.PHONY : src/dependancies/imgui/imgui_widgets.o

# target to build an object file
src/dependancies/imgui/imgui_widgets.cpp.o:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/dependancies/imgui/imgui_widgets.cpp.o
.PHONY : src/dependancies/imgui/imgui_widgets.cpp.o

src/dependancies/imgui/imgui_widgets.i: src/dependancies/imgui/imgui_widgets.cpp.i

.PHONY : src/dependancies/imgui/imgui_widgets.i

# target to preprocess a source file
src/dependancies/imgui/imgui_widgets.cpp.i:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/dependancies/imgui/imgui_widgets.cpp.i
.PHONY : src/dependancies/imgui/imgui_widgets.cpp.i

src/dependancies/imgui/imgui_widgets.s: src/dependancies/imgui/imgui_widgets.cpp.s

.PHONY : src/dependancies/imgui/imgui_widgets.s

# target to generate assembly for a file
src/dependancies/imgui/imgui_widgets.cpp.s:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/dependancies/imgui/imgui_widgets.cpp.s
.PHONY : src/dependancies/imgui/imgui_widgets.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mesh.o: src/mesh.cpp.o

.PHONY : src/mesh.o

# target to build an object file
src/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/mesh.cpp.o
.PHONY : src/mesh.cpp.o

src/mesh.i: src/mesh.cpp.i

.PHONY : src/mesh.i

# target to preprocess a source file
src/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/mesh.cpp.i
.PHONY : src/mesh.cpp.i

src/mesh.s: src/mesh.cpp.s

.PHONY : src/mesh.s

# target to generate assembly for a file
src/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/mesh.cpp.s
.PHONY : src/mesh.cpp.s

src/shaders.o: src/shaders.cpp.o

.PHONY : src/shaders.o

# target to build an object file
src/shaders.cpp.o:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/shaders.cpp.o
.PHONY : src/shaders.cpp.o

src/shaders.i: src/shaders.cpp.i

.PHONY : src/shaders.i

# target to preprocess a source file
src/shaders.cpp.i:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/shaders.cpp.i
.PHONY : src/shaders.cpp.i

src/shaders.s: src/shaders.cpp.s

.PHONY : src/shaders.s

# target to generate assembly for a file
src/shaders.cpp.s:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/shaders.cpp.s
.PHONY : src/shaders.cpp.s

src/transform.o: src/transform.cpp.o

.PHONY : src/transform.o

# target to build an object file
src/transform.cpp.o:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/transform.cpp.o
.PHONY : src/transform.cpp.o

src/transform.i: src/transform.cpp.i

.PHONY : src/transform.i

# target to preprocess a source file
src/transform.cpp.i:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/transform.cpp.i
.PHONY : src/transform.cpp.i

src/transform.s: src/transform.cpp.s

.PHONY : src/transform.s

# target to generate assembly for a file
src/transform.cpp.s:
	$(MAKE) -f CMakeFiles/object-viewer.dir/build.make CMakeFiles/object-viewer.dir/src/transform.cpp.s
.PHONY : src/transform.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... object-viewer"
	@echo "... src/dependancies/imgui/imgui.o"
	@echo "... src/dependancies/imgui/imgui.i"
	@echo "... src/dependancies/imgui/imgui.s"
	@echo "... src/dependancies/imgui/imgui_demo.o"
	@echo "... src/dependancies/imgui/imgui_demo.i"
	@echo "... src/dependancies/imgui/imgui_demo.s"
	@echo "... src/dependancies/imgui/imgui_draw.o"
	@echo "... src/dependancies/imgui/imgui_draw.i"
	@echo "... src/dependancies/imgui/imgui_draw.s"
	@echo "... src/dependancies/imgui/imgui_impl_glfw.o"
	@echo "... src/dependancies/imgui/imgui_impl_glfw.i"
	@echo "... src/dependancies/imgui/imgui_impl_glfw.s"
	@echo "... src/dependancies/imgui/imgui_impl_opengl3.o"
	@echo "... src/dependancies/imgui/imgui_impl_opengl3.i"
	@echo "... src/dependancies/imgui/imgui_impl_opengl3.s"
	@echo "... src/dependancies/imgui/imgui_widgets.o"
	@echo "... src/dependancies/imgui/imgui_widgets.i"
	@echo "... src/dependancies/imgui/imgui_widgets.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mesh.o"
	@echo "... src/mesh.i"
	@echo "... src/mesh.s"
	@echo "... src/shaders.o"
	@echo "... src/shaders.i"
	@echo "... src/shaders.s"
	@echo "... src/transform.o"
	@echo "... src/transform.i"
	@echo "... src/transform.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

